# Generated by Django 4.0.9 on 2023-02-16 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['-created_at'], 'verbose_name': 'Item', 'verbose_name_plural': 'Items'},
        ),
    ]
