# Generated by Django 4.0.9 on 2023-02-17 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_item_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='currency',
            field=models.CharField(choices=[('₽', 'RUB'), ('$', 'USD')], default='₽', max_length=3),
        ),
    ]
